name: Generate File List

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate file list
        run: |
          cd files
          # Changed output from list.json to list.txt
          find . -type f | sed 's|^\./||' | grep -v '^\.DS_Store$' | grep -v '^list\.txt$' > list.txt
          cd ..
      
      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          # Changed to add list.txt
          git add files/list.txt
          git diff --staged --quiet || git commit -m "Update file list"
          git push