name: Generate File List

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate file list with sizes
        run: |
          cd files
          # This new command finds files and prints their path and size in bytes, separated by a pipe |.
          find . -type f -printf '%p|%s\n' | sed 's|^\./||' | grep -v '^\.DS_Store' | grep -v '^list\.txt' > list.txt
          cd ..
      
      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add files/list.txt
          git diff --staged --quiet || git commit -m "Update file list"
          git push