name: Generate File List

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate file list
        run: |
          cd files
          find . -type f | sed 's|^\./||' | grep -v '^\.DS_Store$' | grep -v '^list\.json$' > ../list.json
          cd ..
      
      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add list.json
          git diff --staged --quiet || git commit -m "Update file list"
          git push