name: Generate File List

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # --- THIS IS THE FIX ---
    # Grant the action permission to write to the repository
    permissions:
      contents: write
    # -----------------------

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate file list
        run: |
          # Create the list.json file inside the /files directory
          cd files
          find . -type f | sed 's|^\./||' | grep -v '^\.DS_Store$' | grep -v '^list\.json$' > list.json
          cd ..
      
      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add files/list.json
          git diff --staged --quiet || git commit -m "Update file list"
          git push